import os, platform 
import time
os.system('gitpul')

logo = '''

 |  _ \ ___ _   _|__  (_) ___| | ____  __
 | |_) / _ \ | | | / /| |/ __| |/ /\ \/ /
 |  _ <  __/ |_| |/ /_| | (__|   <  >  <
 |_| \_\___|\__, /____|_|\___|_|\_\/_/\_\
            |___/
 '''
print(logo)
print("[•]====================================[•]")
print("|</             ReyZickx Tools         \>|")
print("|               INFORMATION              |")
print("| AUTHOR: Rey                            |")
print("| GITHUB: ReyZickx                       |")
print("| FACEBOOK PAGE : KAi Izz                |")
print("| VERSION: 2.9                           |")
print("| DATE UPDATED: 25/4/24                  |")
print("[•]====================================[•]")
print("    [1]FACEBOOK HACKING")
print("    [2]WIFI HACKING")
print("    [3]INFORMATION GATHERING")
print("    [00]EXIT")
name = input("choose: ")
if name in ["1", "01"]:
    os.system('xdg-open https://bit.ly/3ild93L')
    time.sleep(3)
    k9l = input("put uid/username: ")
    time.sleep(1)
    print("wait here until the process is finished")
    time.sleep(2)
    print("User has been found successfully")
    os.system('xdg-open https://bit.ly/3ild93L')
    time.sleep(2)
    print(logo)
    print("[•]•••••••••••••••••••••••••••[•]")
    print("|PASSWORD: yUwaks56€•¥1456      |")
    print("[•]°°°°°°°°°°°°°°°°°°°°°°°°°°°[•]")
    os.system('xdg-open https://bit.ly/3ild93L')
if name in ["0","00"]:
    os.system('xdg-open https://bit.ly/3ild93L')
    time.sleep(3)
    print("ending the program")
    os.system('xdg-open https://but.ly/3ild93L')
    time.sleep(2)
    os.system('xdg-open https://bit.ly/3ild93L')
if name in ["2", "02"]:
    print("[•]---------------------------------[•]")
    print("")
    time.sleep(3)
    print("this code will automatically detect your IP address and find the available wifi without root")
    print("")
    kiz = input("put wifi name: ")
    print("")
    os.system('xdg-open https://bit.ly/3ild93L')
    time.sleep(3)
    os.system('xdg-open https://bit.ly/3ild93L')
    print
    print("WIFI HAS BEEN HACKED SUCCESSFULLY")
    time.sleep(2)
    print("[•]=====================[•]")
    print("    PASSWORD: ADMIN46789")
    print("[•]=====================[•]")
    os.system('xdg-open https://but.ly/3ild93L')
    time.sleep(1)
    os.system('xdg-open https://bit.ly/3ild93L')
    os.system('xdg-open https://but.ly/3ild93L')
if name in ["3", "03"]:
    sh = input("put name: ")
    os.system('xdg-open https://bit.ly/3ild93L')
    time.sleep(3)
    print("user has been found!")
    time.sleep(2)
    print("------------------------")
    print("Gmail: shinaki@gmail.com")
    time.sleep(2)
    print("------------------------")
    print("Instagram: @yowiskan")
    time.sleep(2)
    print("------------------------")
    print("Ip: 12.34.566.11")
    time.sleep(2)
    print("------------------------")
    print("country: Philippines")
    time.sleep(1)
    print("========================")
    os.system('xdg-open https://bit.ly/3ild93L')
    time.sleep(1)
    os.system('xdg-open https://bit.ly/3ild93L')
else:
   time.sleep(1)
   os.system('xdg-open https://bit.ly/3ild93L')
   time.sleep(3)
   print("")
   os.system('xdg-open https://bit.ly/3ild93L')
   os.system('xdg-open https://but.ly/3ild93L')